apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_secret_access_key: k4fUehID/BM3+Ic67WQE1wggu4o1ejVIJ7bdYDgb
  aws_session_token: FwoGZXIvYXdzEGIaDDspTo+TCDwLWIQDPyLVAc3usj8RC9fgRiWZ4d1GycvLgZRD1iaLKXzFUn36tkD2SuyZSR7aTChoPcZHOTSUEiulhdmrgQLHQw8d1n/HBhG/FIDB3QTmQROVM7/UNij5hmJsYDuMU8ckc4C/AEkz39fubMVV/bkfNUhSIHI7ZEHeXZj3srHsC1pWGkC79Htvx8om0lXEJxz3dM24iW74c4N+6Pd96SFzcw2McDj+8mRxnVVOi+9vgMUrFE9aYvKMmT/5ueEIcQmPd8/YWg57RU6+dGSVzxboAJHn7q7Pcylfxk8U7Cjz7pCZBjItKNpZbv8Xhz5RiQEKnsiKSnuZh7pxKsd/CBI7q+bt82XAjfCb8uLxsylIswKJ
