name: Docker Build Image and Push

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_TOKEN}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker Image udagram-reverseproxy
        run: docker build -t udagram-reverseproxy ./reverseproxy
          docker tag udagram-api-feed ${{DOCKER_USER}}/reverseproxy

      - name: Build the Docker Image udagram-api-user
        run: docker build -t udagram-api-user ./udagram-api-user
          docker tag udagram-api-feed ${{DOCKER_USER}}/udagram-api-user

      - name: Build the Docker Image udagram-api-feed
        run: docker build -t udagram-api-feed ./udagram-api-feed
          docker tag udagram-api-feed ${{DOCKER_USER}}/udagram-api-feed:v1

      - name: Build the Docker Image udagram-frontend
        run: docker build -t udagram-frontend ./udagram-frontend
          docker tag udagram-api-feed ${{DOCKER_USER}}/udagram-frontend

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v2
    #   - name: Login to Docker Hub
    #     uses: docker/login-action@v1
    #     with:
    #       username: ${{ secrets.DOCKER_USER }}
    #       password: ${{ secrets.DOCKER_TOKEN }}
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Build and push reverseproxy
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./udagram-reverseproxy/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USER}}/simplewhale:latest
    # - name: Build and push udagram-api-user
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./udagram-api-user/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USER}}/simplewhale:latest
    # - name: Build and push udagram-api-feed
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./udagram-api-feed/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USER}}/simplewhale:latest
    # - name: Build and push udagram-frontend
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./udagram-frontend/Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKER_USER}}/simplewhale:latest
